修复在SDGB下直接SetNextProcess导致摄像头未能正确关闭而引发的帧率波动
hykilpikonna/AquaDX pull request #73
Opened 2024-10-22 13:06 UTC by Fukimes

技术水平有限，貌似
SingletonStateMachine<AmManager, AmManager.EState>.Instance.AimeReader.EnableRead(false);
SingletonStateMachine<AmManager, AmManager.EState>.Instance.AimeReader.BeginPlay();
无法直接终止摄像头扫描（

2024-10-22 13:23 UTC, hykilpikonna approved these changes

2024-10-22 13:31 UTC, clansty requested changes

2024-10-22 13:31 UTC, clansty commented on AquaMai/UX/SinglePlayer.cs
> +        public static bool SDGB_Check() {
我觉得这个东西在 Helper 里面开一个 Constants 类，然后把获取 GameID 的逻辑写进去。因为别的地方也需要这个逻辑，比如说自定义摄像头 ID 之前就做过这个

2024-10-22 13:31 UTC, clansty commented on AquaMai/UX/SinglePlayer.cs
> +        public static bool IsSDGB { get; set; } = SDGB_Check();
这个也不要了

2024-10-22 13:31 UTC, clansty commented on AquaMai/UX/SinglePlayer.cs
> +            if (SinglePlayer.IsSDGB != true){ __instance.Process.SetNextProcess();}
这里直接写 Constants.GameID != "SDGB"

2024-10-22 13:55 UTC, WYH2004-MC commented on AquaMai/UX/SinglePlayer.cs
> +        public static bool SDGB_Check() {
https://github.com/hykilpikonna/AquaDX/pull/66 已经写了个[GameInfo](https://github.com/hykilpikonna/AquaDX/blob/v1-dev/AquaMai/Utils/GameInfo.cs)类在Utils里面

2024-10-22 13:59 UTC, Fukimes commented on AquaMai/UX/SinglePlayer.cs
> +        public static bool SDGB_Check() {
收到，那直接调用就行

2024-10-22 14:18 UTC, Menci requested changes

2024-10-22 14:18 UTC, Menci commented on AquaMai/UX/SinglePlayer.cs
> +            if (!GameInfo.GetGameId().Equals("SDGB")) { __instance.Process.SetNextProcess();}
这是把跳过倒计时给取消了？是不是应该保持跳过倒计时把摄像头释放，或者直接从头干掉降低帧率

2024-10-22 14:18 UTC, Menci commented on AquaMai/UX/SinglePlayer.cs
> +            if (GameInfo.GetGameId().Equals("SDGB")) { return true; }
单行不要加花括号，要加花括号就换三行

2024-10-22 14:18 UTC, Menci commented on .vs/VSWorkspaceState.json
> +}
是不是没 ignore 掉

2024-10-22 14:22 UTC, closed without merging

2024-10-22 14:24 UTC, Fukimes commented
我发现单纯不进行SetNextProcess并不能解决根本问题，目前发现开始扫码之后，若跳过倒计时不进入游戏，仍会掉帧。正确关闭摄像头才是正确的（

2024-10-22 15:10 UTC, Zaphkito commented
首先我建议将某些代码和正儿八经的singleplayer分开，这些不应该全部写到singleplayer.cs里

2024-10-23 16:54 UTC, clansty commented on AquaMai/UX/SinglePlayer.cs
> +        public static bool SDGB_Check() {
> #66 已经写了个[GameInfo](https://github.com/hykilpikonna/AquaDX/blob/v1-dev/AquaMai/Utils/GameInfo.cs)类在Utils里面

草，这玩意应该放 Helpers 里面啊